target-version = "py311"

[lint]
select = ["ALL"]
ignore = [
    "ERA001",  # Commented-out code.
    
    "S101",  # Use of `assert` statement.
    "RET504",  # Assignment right before return.
    
    "COM812", # Missing commas.
    "FIX002",
    "TD003",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = [
    "ALL",
]
unfixable = []

[format]
# Like Black, use double quotes for strings.
quote-style = "double"
