target-version = "py311"

[lint]
select = ["ALL"]
ignore = [
    "ERA001",  # Commented-out code.
    
    "S101",  # Use of `assert` statement.
    "RET504",  # Assignment right before return.
    "COM812", # Missing comma at the end of a function call. Bad in show() call.
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = [
    "ALL",
    "COM812", # Add missing commas automatically.
]
unfixable = []

[format]
# Like Black, use double quotes for strings.
quote-style = "double"
